# PyTorch - MNIST

## Resources
https://www.aiworkbox.com/lessons/load-mnist-dataset-from-pytorch-torchvision

## Code Reference
https://gist.github.com/kdubovikov/eb2a4c3ecadd5295f68c126542e59f0a

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.autograd import Variable

In [2]:
import pdb

In [3]:
import time

In [4]:
# download and transform train dataset
# train_check = torch.utils.data.DataLoader(datasets.MNIST('../mnist_data', 
#                                                    download=True,
#                                                         train=True))

# test_check = torch.utils.data.DataLoader(datasets.MNIST('../mnist_data', 
#                                                    download=True,
#                                                         train=False))
# print(len(train_check))
# print(len(test_check))

In [5]:
# Turn down for faster convergence
t0 = time.time()

# download and transform train dataset
train_loader = torch.utils.data.DataLoader(datasets.MNIST('../mnist_data', 
                                                          download=True, 
                                                          train=True,
                                                          transform=transforms.Compose([
                                                              transforms.ToTensor(), # first, convert image to PyTorch tensor
                                                              transforms.Normalize((0.1307,), (0.3081,)) # normalize inputs
                                                          ])), 
                                           batch_size=10, 
                                           shuffle=True)

# download and transform test dataset
test_loader = torch.utils.data.DataLoader(datasets.MNIST('../mnist_data', 
                                                          download=True, 
                                                          train=False,
                                                          transform=transforms.Compose([
                                                              transforms.ToTensor(), # first, convert image to PyTorch tensor
                                                              transforms.Normalize((0.1307,), (0.3081,)) # normalize inputs
                                                          ])), 
                                           batch_size=10, 
                                           shuffle=True)


In [10]:
#prseudo code for train
for i, dict_ in enumerate(train_loader):
    images  = dict_['img']
    target  = dict_['target'].type(torch.FloatTensor)
    
    if USE_CUDA:
        images = images.cuda()
        target = target.cuda()
    
    images = Variable(images)
    target = Variable(target)

    #train net
    #prediction = Net().forward(images)
    #....
    
    #for kernel:
    print(target)
    if i ==0 : break

TypeError: list indices must be integers or slices, not str

In [9]:
for data, target in test_loader:
    print(target)

tensor([1, 5, 3, 6, 8, 5, 8, 5, 1, 6])
tensor([1, 2, 0, 3, 5, 4, 5, 2, 5, 9])
tensor([9, 4, 6, 1, 6, 5, 3, 4, 0, 8])
tensor([0, 1, 4, 3, 6, 2, 3, 7, 5, 5])
tensor([3, 2, 2, 4, 7, 3, 4, 4, 1, 1])
tensor([1, 3, 4, 5, 6, 0, 0, 9, 5, 8])
tensor([5, 9, 7, 8, 6, 8, 8, 2, 0, 1])
tensor([1, 9, 2, 3, 0, 6, 1, 4, 2, 0])
tensor([3, 1, 5, 6, 3, 7, 8, 8, 3, 7])
tensor([4, 0, 6, 0, 2, 9, 5, 6, 6, 8])
tensor([0, 5, 4, 5, 9, 5, 5, 4, 9, 6])
tensor([8, 2, 8, 7, 1, 1, 0, 4, 9, 0])
tensor([8, 6, 2, 4, 1, 8, 0, 3, 5, 3])
tensor([1, 7, 8, 3, 5, 4, 5, 3, 5, 1])
tensor([4, 7, 1, 2, 7, 6, 7, 9, 1, 2])
tensor([4, 5, 3, 3, 3, 2, 6, 4, 9, 4])
tensor([7, 4, 5, 6, 8, 7, 6, 8, 5, 2])
tensor([8, 1, 5, 9, 5, 2, 2, 7, 7, 6])
tensor([8, 2, 8, 6, 7, 1, 4, 8, 6, 8])
tensor([4, 8, 0, 0, 0, 5, 8, 6, 0, 1])
tensor([2, 5, 7, 0, 3, 3, 9, 2, 6, 2])
tensor([2, 2, 5, 5, 0, 4, 0, 7, 7, 1])
tensor([7, 5, 5, 6, 9, 4, 1, 2, 5, 5])
tensor([9, 1, 0, 8, 7, 4, 6, 7, 5, 7])
tensor([8, 5, 1, 5, 4, 0, 2, 4, 5, 2])
tensor([8, 1, 2, 4, 8, 6,

tensor([3, 0, 7, 8, 7, 6, 7, 3, 1, 8])
tensor([9, 8, 0, 4, 8, 5, 5, 1, 2, 6])
tensor([4, 9, 7, 1, 4, 7, 4, 3, 3, 6])
tensor([9, 5, 3, 5, 6, 9, 8, 8, 0, 9])
tensor([3, 2, 9, 2, 6, 6, 3, 6, 7, 1])
tensor([6, 6, 9, 0, 5, 1, 2, 0, 8, 7])
tensor([3, 5, 7, 3, 0, 3, 5, 2, 8, 9])
tensor([0, 7, 7, 8, 7, 7, 5, 1, 0, 1])
tensor([4, 2, 9, 7, 8, 8, 0, 7, 8, 2])
tensor([5, 7, 5, 2, 0, 8, 2, 4, 3, 0])
tensor([7, 8, 5, 0, 4, 1, 5, 8, 8, 6])
tensor([2, 7, 3, 4, 2, 9, 8, 5, 5, 9])
tensor([6, 5, 6, 9, 5, 6, 6, 1, 5, 2])
tensor([9, 1, 6, 3, 5, 2, 4, 7, 5, 6])
tensor([9, 5, 6, 8, 1, 9, 4, 5, 0, 5])
tensor([5, 8, 8, 8, 7, 9, 1, 8, 9, 0])
tensor([7, 1, 1, 6, 8, 6, 0, 0, 0, 4])
tensor([8, 4, 5, 3, 5, 6, 7, 8, 6, 6])
tensor([2, 8, 7, 8, 6, 0, 0, 1, 1, 0])
tensor([7, 3, 6, 5, 8, 8, 5, 6, 3, 1])
tensor([5, 1, 9, 4, 7, 0, 5, 5, 7, 8])
tensor([8, 9, 2, 4, 3, 5, 4, 8, 3, 2])
tensor([3, 0, 3, 9, 0, 8, 6, 1, 5, 5])
tensor([3, 5, 5, 6, 0, 1, 8, 3, 1, 7])
tensor([5, 9, 1, 1, 8, 6, 2, 0, 2, 2])
tensor([2, 9, 4, 2, 6, 3,

tensor([7, 5, 6, 6, 6, 6, 1, 1, 4, 7])
tensor([4, 6, 8, 9, 8, 2, 5, 9, 0, 8])
tensor([1, 1, 0, 0, 9, 1, 6, 7, 7, 1])
tensor([6, 1, 5, 9, 8, 9, 5, 3, 8, 0])
tensor([5, 7, 6, 4, 5, 5, 0, 5, 6, 0])
tensor([5, 6, 5, 8, 8, 8, 2, 5, 4, 5])
tensor([7, 2, 8, 0, 3, 8, 2, 3, 6, 8])
tensor([1, 2, 3, 3, 2, 5, 9, 1, 4, 5])
tensor([3, 6, 5, 1, 2, 7, 8, 7, 7, 6])
tensor([9, 7, 6, 3, 1, 9, 5, 9, 6, 9])
tensor([2, 8, 0, 1, 0, 3, 2, 3, 4, 2])
tensor([2, 5, 8, 6, 1, 6, 2, 4, 1, 3])
tensor([4, 6, 8, 3, 7, 4, 7, 8, 3, 4])
tensor([1, 4, 7, 0, 5, 7, 3, 4, 6, 6])
tensor([2, 4, 0, 8, 8, 3, 0, 6, 0, 6])
tensor([5, 8, 7, 4, 8, 1, 2, 5, 7, 5])
tensor([1, 9, 1, 9, 3, 7, 3, 2, 6, 0])
tensor([0, 4, 6, 4, 4, 5, 1, 0, 9, 8])
tensor([2, 7, 7, 6, 8, 2, 2, 4, 3, 1])
tensor([2, 6, 9, 4, 9, 1, 7, 7, 4, 1])
tensor([0, 3, 4, 1, 4, 4, 4, 9, 4, 0])
tensor([7, 8, 0, 7, 1, 3, 6, 3, 0, 1])
tensor([7, 6, 4, 5, 0, 8, 9, 0, 8, 1])
tensor([4, 1, 3, 3, 5, 0, 2, 0, 4, 1])
tensor([9, 8, 1, 4, 2, 1, 2, 9, 8, 3])
tensor([6, 1, 4, 9, 6, 4,

tensor([9, 9, 0, 7, 6, 4, 6, 4, 9, 9])
tensor([3, 3, 3, 3, 9, 7, 6, 7, 1, 8])
tensor([1, 0, 7, 0, 4, 8, 3, 9, 9, 0])
tensor([9, 9, 0, 0, 9, 6, 7, 6, 5, 0])
tensor([7, 3, 0, 3, 5, 6, 1, 6, 2, 6])
tensor([8, 5, 0, 1, 1, 0, 0, 2, 9, 0])
tensor([7, 1, 1, 1, 1, 0, 1, 2, 9, 6])
tensor([2, 8, 1, 8, 1, 2, 4, 8, 4, 5])
tensor([6, 8, 6, 3, 5, 1, 8, 8, 7, 7])
tensor([5, 4, 4, 3, 6, 8, 4, 6, 7, 7])
tensor([2, 2, 8, 5, 7, 7, 5, 5, 9, 8])
tensor([9, 6, 3, 2, 0, 8, 2, 1, 9, 7])
tensor([9, 4, 8, 4, 8, 8, 3, 6, 2, 9])
tensor([3, 0, 8, 4, 7, 8, 6, 0, 3, 4])
tensor([5, 4, 5, 5, 7, 7, 6, 6, 9, 2])
tensor([3, 7, 3, 9, 2, 0, 3, 1, 7, 3])
tensor([9, 1, 6, 5, 3, 8, 3, 3, 1, 0])
tensor([0, 0, 8, 0, 6, 3, 7, 4, 2, 2])
tensor([9, 3, 7, 3, 5, 0, 7, 6, 7, 1])
tensor([4, 7, 2, 5, 2, 0, 9, 7, 7, 1])
tensor([9, 6, 9, 4, 6, 0, 1, 6, 5, 1])
tensor([2, 3, 2, 3, 8, 6, 9, 9, 3, 5])
tensor([7, 9, 3, 8, 4, 2, 7, 9, 0, 8])
tensor([7, 1, 0, 8, 8, 9, 0, 6, 6, 7])
tensor([0, 6, 5, 7, 5, 0, 5, 7, 0, 7])
tensor([8, 9, 1, 1, 7, 6,

tensor([8, 6, 8, 3, 7, 6, 5, 9, 0, 7])
tensor([0, 4, 7, 9, 6, 1, 1, 8, 0, 6])
tensor([2, 6, 6, 5, 9, 9, 2, 5, 5, 6])
tensor([0, 2, 4, 6, 5, 4, 6, 4, 0, 3])
tensor([0, 8, 2, 2, 3, 7, 2, 8, 7, 3])
tensor([3, 8, 3, 0, 7, 6, 6, 7, 6, 0])
tensor([4, 0, 0, 1, 2, 1, 1, 7, 6, 3])
tensor([6, 8, 6, 1, 3, 2, 3, 4, 4, 4])
tensor([9, 8, 9, 2, 0, 5, 9, 9, 3, 3])
tensor([7, 3, 6, 3, 4, 0, 6, 0, 2, 9])
tensor([5, 2, 3, 1, 1, 2, 2, 9, 5, 5])
tensor([8, 5, 8, 3, 7, 8, 1, 3, 9, 7])
tensor([0, 8, 1, 3, 7, 6, 5, 0, 0, 0])
tensor([0, 4, 3, 7, 1, 8, 5, 5, 8, 4])
tensor([4, 6, 7, 7, 6, 3, 3, 4, 0, 9])
tensor([3, 3, 2, 0, 0, 4, 8, 1, 8, 0])
tensor([6, 4, 7, 9, 7, 3, 1, 6, 8, 1])
tensor([4, 6, 1, 2, 0, 8, 2, 5, 8, 6])
tensor([0, 9, 8, 5, 2, 4, 1, 6, 3, 0])
tensor([4, 7, 8, 2, 8, 5, 3, 6, 4, 6])
tensor([2, 4, 0, 2, 3, 1, 9, 9, 0, 3])
tensor([5, 6, 7, 6, 8, 5, 0, 7, 7, 1])
tensor([3, 1, 2, 8, 8, 1, 8, 8, 9, 8])
tensor([3, 0, 9, 0, 3, 2, 4, 0, 1, 1])
tensor([9, 8, 9, 6, 6, 1, 4, 4, 9, 4])
tensor([7, 4, 5, 1, 0, 4,

In [17]:

class CNNClassifier(nn.Module):
    """Custom module for a simple convnet classifier"""
    def __init__(self):
        super(CNNClassifier, self).__init__()
        self.conv1 = nn.Conv2d(1, 10, kernel_size=5)
        self.conv2 = nn.Conv2d(10, 20, kernel_size=5)
        self.dropout = nn.Dropout2d()
        self.fc1 = nn.Linear(320, 50)
        self.fc2 = nn.Linear(50, 10)
    
    def forward(self, x):
        # input is 28x28x1
        # conv1(kernel=5, filters=10) 28x28x10 -> 24x24x10
        # max_pool(kernel=2) 24x24x10 -> 12x12x10
        
        # Do not be afraid of F's - those are just functional wrappers for modules form nn package
        # Please, see for yourself - http://pytorch.org/docs/_modules/torch/nn/functional.html
        x = F.relu(F.max_pool2d(self.conv1(x), 2))
        
        # conv2(kernel=5, filters=20) 12x12x20 -> 8x8x20
        # max_pool(kernel=2) 8x8x20 -> 4x4x20
        x = F.relu(F.max_pool2d(self.dropout(self.conv2(x)), 2))
        
        # flatten 4x4x20 = 320
        x = x.view(-1, 320)
        
        # 320 -> 50
        x = F.relu(self.fc1(x))
        x = F.dropout(x, training=self.training)
        
        # 50 -> 10
        x = self.fc2(x)
        
        # transform to logits
        return F.log_softmax(x)

# create classifier and optimizer objects
clf = CNNClassifier()
opt = optim.SGD(clf.parameters(), lr=0.01, momentum=0.5)

loss_history = []
acc_history = []

def train(epoch):
    clf.train() # set model in training mode (need this because of dropout)
    
    # dataset API gives us pythonic batching 
    for batch_id, (data, label) in enumerate(train_loader):
        data = Variable(data)
        target = Variable(label)
        
        # forward pass, calculate loss and backprop!
        opt.zero_grad()
        preds = clf(data)
        loss = F.nll_loss(preds, target)
        loss.backward()
        loss_history.append(loss.data[0])
        opt.step()
        
        if batch_id % 1000 == 0:
            print(loss.data[0])

def test(epoch):
    clf.eval() # set model in inference mode (need this because of dropout)
    test_loss = 0
    correct = 0
    
    for data, target in test_loader:
        data = Variable(data, volatile=True) 
        target = Variable(target)
        
        output = clf(data)
        test_loss += F.nll_loss(output, target).data[0]
        pred = output.data.max(1)[1] # get the index of the max log-probability
        correct += pred.eq(target.data).cpu().sum()

    test_loss = test_loss
    test_loss /= len(test_loader) # loss function already averages over batch size
    accuracy = 100. * correct / len(test_loader.dataset)
    acc_history.append(accuracy)
    print("---------------------------------------")
    print("Epoch %d" % epoch)
    print('\nTest set: Average loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)\n'.format(
        test_loss, correct, len(test_loader.dataset),
        accuracy))

n_epochs = 5    
for epoch in range(0, n_epochs):
    #print("Epoch %d" % epoch)
    train(epoch)
    test(epoch)

run_time = time.time() - t0
print('Example run in : %.3f s' % run_time)
    
print("-----------------------")
print("the end")
print("-----------------------") 

/Users/reshamashaikh/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:60: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
/Users/reshamashaikh/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:82: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
/Users/reshamashaikh/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:86: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number


tensor(2.1927)
tensor(0.8229)
tensor(1.2104)
tensor(0.2929)
tensor(0.3941)
tensor(0.1906)


/Users/reshamashaikh/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:94: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
/Users/reshamashaikh/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:98: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number


---------------------------------------
Epoch 0

Test set: Average loss: 0.0915, Accuracy: 9719/10000 (97%)

tensor(0.2538)
tensor(0.4179)
tensor(0.0715)
tensor(0.5447)
tensor(0.0156)
tensor(0.2156)
---------------------------------------
Epoch 1

Test set: Average loss: 0.0735, Accuracy: 9767/10000 (97%)

tensor(1.0025)
tensor(0.1476)
tensor(0.0214)
tensor(0.2380)
tensor(0.0744)
tensor(0.2105)
---------------------------------------
Epoch 2

Test set: Average loss: 0.0591, Accuracy: 9818/10000 (98%)

tensor(0.0858)
tensor(0.0491)
tensor(0.7070)
tensor(0.0948)
tensor(0.0416)
tensor(0.4938)
---------------------------------------
Epoch 3

Test set: Average loss: 0.0540, Accuracy: 9824/10000 (98%)

tensor(0.1861)
tensor(0.4706)
tensor(0.0168)
tensor(0.0122)
tensor(0.0811)
tensor(0.3399)
---------------------------------------
Epoch 4

Test set: Average loss: 0.0514, Accuracy: 9834/10000 (98%)

Example run in : 174.381 s
-----------------------
the end
-----------------------


https://am207.github.io/2018spring/wiki/ValidationSplits.html


In [ ]:
#train

In [ ]:
#mnist_trainset

In [ ]:
#!ls -a ./data

In [ ]:
#!ls -alt ./data/processed/