## PyTorch - Check Setup

In [1]:
!conda --version

conda 4.5.10


In [2]:
!python --version

Python 3.6.5 :: Anaconda, Inc.


In [3]:
import sys
print("Python Version:", sys.version)

Python Version: 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]


In [4]:
!pip list | grep pandas

pandas                             0.23.0   


---

In [25]:
import numpy as np

In [48]:
# create an empty 2-d Numpy array
np.random.seed(0)
x = np.empty([5,3])

In [49]:
print(type(x))
print(len(x))
print(x.shape)
print(x)

<class 'numpy.ndarray'>
5
(5, 3)
[[ 8.40e-323  0.00e+000  0.00e+000]
 [ 0.00e+000  0.00e+000  0.00e+000]
 [ 0.00e+000  0.00e+000  0.00e+000]
 [ 0.00e+000  0.00e+000  0.00e+000]
 [ 0.00e+000  6.95e-310 -2.32e+077]]


In [55]:
#And suppress suppresses the use of scientific notation for small numbers:
np.set_printoptions(precision=3, suppress=True)
print(x)

[[ 8.399e-323  0.000e+000  0.000e+000]
 [ 0.000e+000  0.000e+000  0.000e+000]
 [ 0.000e+000  0.000e+000  0.000e+000]
 [ 0.000e+000  0.000e+000  0.000e+000]
 [ 0.000e+000  6.953e-310 -2.316e+077]]


In [45]:
# create a 2x2 matrix Numpy 2-d array of zeroes

In [12]:
y = np.zeros((2, 2), dtype=int)

In [13]:
print(type(y))
print(y.shape)
print(y)

<class 'numpy.ndarray'>
(2, 2)
[[0 0]
 [0 0]]


In [14]:
# create a vector Numpy 1-d array of random integers

In [17]:
np.random.seed(0)
z = np.random.randint(15, size=(8,1)).astype('int')

In [18]:
print(type(z))
print(z.shape)
print(z)

<class 'numpy.ndarray'>
(8, 1)
[[12]
 [ 5]
 [ 0]
 [ 3]
 [11]
 [ 3]
 [ 7]
 [ 9]]


---

In [19]:
import torch

In [40]:
# construct a 5x3 matrix, uninitialized
x = torch.empty(5, 3)
print(type(x))
print(len(x))
print(x.shape)
print(x)


<class 'torch.Tensor'>
5
torch.Size([5, 3])
tensor([[ 0.0000e+00, -8.5899e+09,  0.0000e+00],
        [-8.5899e+09,  5.6052e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00, -8.5899e+09,  3.2982e+24]])


In [41]:
y = torch.rand(5, 3)
print(type(y))
print(len(y))
print(y.shape)
print(y)

<class 'torch.Tensor'>
5
torch.Size([5, 3])
tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341],
        [0.4901, 0.8964, 0.4556],
        [0.6323, 0.3489, 0.4017],
        [0.0223, 0.1689, 0.2939]])


In [60]:
print(y.data[0])

tensor([0.4963, 0.7682, 0.0885])


In [61]:
print(y.size())

torch.Size([5, 3])


In [42]:
z = torch.zeros(5, 3, dtype=torch.long)
print(type(z))
print(len(z))
print(z.shape)
print(z)

<class 'torch.Tensor'>
5
torch.Size([5, 3])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


tensor(0)
