## PyTorch - AutoGrad (automatic differentiation)

In [1]:
import torch

In [2]:
# the python debugger
import pdb

In [ ]:
from torch.autograd import Variable

x = Variable(torch.randn(1, 10))
prev_h = Variable(torch.randn(1, 20))
W_h = Variable(torch.randn(20, 20))
W_x = Variable(torch.randn(20, 10))

pdb.set_trace()

i2h = torch.mm(W_x, x.t())
h2h = torch.mm(W_h, prev_h.t())

next_h = i2h + h2h
next_h = next_h.tanh()

--Return--
> <ipython-input-3-8e2d6f24d830>(8)<module>()->None
-> pdb.set_trace()
(Pdb) a
(Pdb) v
*** NameError: name 'v' is not defined
(Pdb) x
tensor([[ 0.2406, -2.1995, -0.3088, -0.9960,  1.1188,  0.9809,  0.1124,  0.1503,
         -0.9284,  1.1889]])
(Pdb) prev_h
tensor([[ 0.2227,  0.0499, -0.9019,  0.0652,  0.0026,  1.4007,  0.3241, -0.7835,
         -1.5462, -0.4036, -0.7867,  0.3975,  0.4649,  1.3110, -0.3008,  0.6338,
         -0.5250, -1.9106, -0.2453, -0.6971]])
(Pdb) W_h
tensor([[-0.4750,  0.3251, -1.4694,  0.1566, -1.2948, -1.3354,  1.4007, -0.5003,
          0.0045, -2.1496, -0.1962,  0.4213,  0.8803,  0.0571, -1.9084,  0.9993,
          1.0485, -1.2454, -0.2734,  0.2367],
        [-0.2207, -0.7762, -0.5875,  0.2857, -1.6234, -0.5717, -0.5769,  0.6784,
         -0.9650, -0.5629,  1.8365,  0.9704, -2.3469,  1.1656, -0.0102, -0.2687,
          1.1875, -1.2333, -0.6341,  0.6625],
        [ 3.4684, -0.2243, -0.3495,  2.0113, -0.7801,  0.7691,  0.1414,  1.2809,
         -0.9840

In [ ]:
x

In [ ]:
type(x)

In [ ]:
x.size

In [ ]:
x.type